// Static brand data with optimized descriptions and keywords - Full sets only
export const staticBrands = [
  {
    id: "1",
    name: "Total Gas Uganda",
    brand: "Total",
    image_url_6kg: "/images/total 6KG.png",
    image_url_12kg: "/images/total 12KG.png",
    price_6kg: "UGX 170,000",
    price_12kg: "UGX 350,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },
  {
    id: "2",
    name: "Shell Gas Uganda",
    brand: "Shell",
    image_url_6kg: "/images/shell 6KG.png",
    image_url_12kg: "/images/shell 12KG.png",
    price_6kg: "UGX 165,000",
    price_12kg: "UGX 300,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },
  {
    id: "3",
    name: "Oryx Gas Uganda",
    brand: "Oryx",
    image_url_6kg: "/images/oryx 6KG.png",    
    price_6kg: "UGX 165,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },
  {
    id: "4",
    name: "Stabex Gas Uganda",
    brand: "Stabex",
    image_url_6kg: "/images/stabex 6KG.png",
    image_url_12kg: "/images/stabex 12KG.png",
    price_6kg: "UGX 150,000",
    price_12kg: "UGX 280,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },
  {
    id: "5",
    name: "Hass Gas Uganda",
    brand: "Hass",
    image_url_6kg: "/images/hass 6KG.png",    
    price_6kg: "UGX 150,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },
  {
    id: "6",
    name: "Ultimate Gas Uganda",
    brand: "Ultimate",
    image_url_6kg: "/images/ultimate 6.png", 
    image_url_12kg: "/images/ultimate 13.png",   
    price_6kg: "UGX 140,000",
    price_12kg: "UGX 280,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  },

  {
    id: "7",
    name: "Nova Gas",
    brand: "Nova",
    image_url_6kg: "/images/Nova 6kg.png",
    image_url_12kg: "/images/Nova 12kg.png",
    price_6kg: "UGX 140,000",
    price_12kg: "UGX 280,000",
    description_6kg: "Comes with gas, burner and grill.",
    description_12kg: "Comes with gas, regulator and horse pipe"
  }

];

// Expanded refill brands data with comprehensive pricing for all common brands
export const refillBrands = [
  {
    id: "1",
    name: "Total Gas Uganda",
    brand: "Total",
    logo_url: "/images/brand_logos/total_logo.png",
    refill_price_3kg: "UGX 30,000",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "2",
    name: "Shell Gas Uganda",
    brand: "Shell",
    logo_url: "/images/brand_logos/shell_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "3",
    name: "Oryx Gas Uganda",
    brand: "Oryx",
    logo_url: "/images/brand_logos/oryx_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "4",
    name: "Stabex Gas Uganda",
    brand: "Stabex",
    logo_url: "/images/brand_logos/stabex_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "5",
    name: "Hass Gas Uganda",
    brand: "Hass",
    logo_url: "/images/brand_logos/hass_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "6",
    name: "Vivo Energy Gas Uganda",
    brand: "Vivo Energy",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "7",
    name: "Taifa Gas Uganda",
    brand: "Taifa",
    logo_url: "/images/brand_logos/taifa_logo.png",
    refill_price_3kg: "UGX 30,000",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "8",
    name: "Meru Gas Uganda",
    brand: "Meru",
    logo_url: "/images/brand_logos/meru_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "9",
    name: "Ven Gas Uganda",
    brand: "Ven Gas",
    logo_url: "/images/brand_logos/vengas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "10",
    name: "Ola Energy Gas Uganda",
    brand: "Ola Energy",
    logo_url: "/images/brand_logos/ola_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "11",
    name: "Ultimate Gas Uganda",
    brand: "Ultimate",
    logo_url: "/images/brand_logos/ultimate_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "12",
    name: "K Gas Uganda",
    brand: "K Gas",
    logo_url: "/images/brand_logos/k_gas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "13",
    name: "C Gas Uganda",
    brand: "C Gas",
    logo_url: "/images/brand_logos/c_gas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "14",
    name: "Hashi Gas Uganda",
    brand: "Hashi",
    logo_url: "/images/brand_logos/hashi_gas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "15",
    name: "Nova Gas Uganda",
    brand: "Nova",
    logo_url: "/images/brand_logos/nova_gas_logo.png",
    refill_price_3kg: "UGX 30,000",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "16",
    name: "Mogas Gas Uganda",
    brand: "Mogas",
    logo_url: "/images/brand_logos/mogas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "17",
    name: "Safe Gas Uganda",
    brand: "Safe",
    logo_url: "/images/brand_logos/safe_gas_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
  {
    id: "18",
    name: "Star Gas Uganda",
    brand: "Star",
    logo_url: "/images/brand_logos/star_logo.png",
    refill_price_6kg: "UGX 50,000",
    refill_price_12kg: "UGX 100,000",
  },
];