
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxhwjoysctshyqukznvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aHdqb3lzY3RzaHlxdWt6bnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzg0NDUsImV4cCI6MjA1ODc1NDQ0NX0.KtaM8W9pTWtdKKC3cbxSMFy5h9o7yR9LqMyRKfD8trA";

// Create a client that can handle database operations
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

try {
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: true
    }
  });
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  // Create a minimal fallback client
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false
    }
  });
}

export const supabase = supabaseInstance!;
export { SUPABASE_URL };
